# Generated by Django 5.2.4 on 2025-07-17 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_project_status', models.CharField(default='IN_PROGRESS', max_length=20)),
                ('default_priority', models.CharField(default='MEDIUM', max_length=20)),
                ('show_completed_tasks', models.BooleanField(default=True)),
                ('enable_templates', models.BooleanField(default=False)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('date_format', models.CharField(default='MM/DD/YYYY', max_length=20)),
                ('refresh_interval', models.IntegerField(default=60)),
                ('items_per_page', models.IntegerField(default=25)),
                ('enable_animations', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
